# File: docker/Dockerfile.tensorboard

FROM python:3.10-slim

RUN pip install --no-cache-dir \
    numpy==1.24.4 \
    six \
    protobuf==4.23.4 \
    tensorboard==2.13.0

WORKDIR /app

# This will pick up ALL runs inside the "dqn" subdirectory.
CMD ["tensorboard", "--logdir=/tensorboard_logs", "--host=0.0.0.0", "--port=6006"]
