FROM python:3.10-slim

WORKDIR /api

COPY ../api /api
COPY ../requirements.txt /api/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5005

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5005"]
